title: Soumik Ghosh
url: "https://ankitsultana.com"
baseurl: "/home"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "© Copyright 2025 Soumik Ghosh. Powered by Jekyll and Github. Last updated: December 10, 2025."

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/home/"
 - name: "CV"
   link: "https://drive.google.com/file/d/1CNT2Ua7UnT8gHBj956G3HlqEPpyqhkhk/view?usp=sharing"
 - name: "Contact"
   link: "contact"
